# Generated by Django 3.0.7 on 2022-08-11 06:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название статьи')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст статьи')),
                ('category', models.CharField(choices=[('ID', 'Idea'), ('LN', 'Learn'), ('mt', 'Motivation'), ('bl', 'Blog')], default='bl', max_length=2)),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Article', verbose_name='Изображение')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('content', tinymce.models.HTMLField(null=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-id', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a article genre (e.g. learn, idea, motivation, gallery)', max_length=256, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('pub_date_comment', models.DateTimeField(auto_now_add=True, verbose_name='Дата написании')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Article')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-id', '-pub_date_comment'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this article', to='frontend.Genre'),
        ),
    ]
