interface DATAPOSTSItem {
	id: number,
	category: string,
	title: string,
	text: string,
	img: string
}

// Примерные данные статей
const DATAPOSTS: DATAPOSTSItem[] = [
	{
		id: 1,
		category: 'Markets',
		title: 'Bearish investor Boaz Weinstein is feeling the pain from this year\'s unexpected stock rally',
		text: "The Enneagram is the latest personality typology to penetrate the zeitgeist. From Hogwarts houses to horoscopes, humans love to categorize ourselves.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 2,
		category: 'NEWS',
		title: 'Enneagrams are the new horoscopes',
		text: "Tracy Anderson memberships are the ultimate Hamptons status symbol. But some devotees say the classes have turned into a chaotic, overpriced mess.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 3,
		category: 'RETAIL',
		title: 'Chaos in the Hamptons: Tracy Anderson devotees gripe about $5,500 mats, $90 classes, and power struggles among \'queen bees\'',
		text: "PAK'nSAVE's money-saving bot used ChatGPT to recommend recipes based on leftover ingredients, but it offered up some potentially deadly combinations.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 4,
		category: 'TECH',
		title: 'Months after an AI deepfake of the pontiff in a puffy coat went viral, Pope Francis is warning about the dangers of AI',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 5,
		category: 'AFRICA',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 6,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 7,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 8,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 9,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 10,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 11,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 12,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 13,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 14,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 15,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 16,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 17,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 18,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 19,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
	{
		id: 20,
		category: 'ECONOMY',
		title: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
		text: "The Vatican released a statement where Pope Francis speaks on AI, its potential harm, and need for tech to service humanity.",
		img: "http://dummyimage.com/300x200/4d494d/686a82.jpeg&text=placeholder+image",
	},
];

export default DATAPOSTS;