# Generated by Django 4.1.1 on 2022-10-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('title', models.CharField(help_text='Название статьи', max_length=255, primary_key=True, serialize=False, verbose_name='Заголовок статьи')),
                ('description', models.TextField(verbose_name='Текст статьи')),
                ('img', models.ImageField(upload_to='Articles/% Y/% m/% d/', verbose_name='Изображение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статья',
                'ordering': ('-time_create', 'title'),
            },
        ),
    ]
