# Generated by Django 4.1.1 on 2022-10-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('title', models.CharField(help_text='Название статьи', max_length=255, primary_key=True, serialize=False, verbose_name='Заголовок статьи')),
                ('description', models.TextField(verbose_name='Текст статьи')),
                ('img', models.ImageField(upload_to='Articles/% Y/% m/% d/', verbose_name='Изображение')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Публикация статьи')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление статьи')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
    ]
