# Generated by Django 4.1.1 on 2022-10-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-time_create', 'title'), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
