# Generated by Django 4.1.1 on 2023-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
