# Generated by Django 4.1.1 on 2023-09-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='views',
            field=models.ManyToManyField(blank=True, editable=False, related_name='post_views', to='articles.ip'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
