# Generated by Django 4.2.11 on 2025-02-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of change'),
        ),
    ]
