# Generated by Django 4.2.11 on 2024-10-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='popularity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='popularity',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
