# Generated by Django 4.1.1 on 2022-10-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-time_update', '-time_create'), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
