# Generated by Django 4.2.8 on 2023-12-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_views_alter_ip_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('title', models.CharField(help_text='Название статьи', max_length=255, primary_key=True, serialize=False, verbose_name='Заголовок статьи')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('slug', models.SlugField(default='', editable=False, max_length=255, verbose_name='URL')),
                ('description', models.TextField(verbose_name='The text of the bond')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of change')),
                ('price', models.FloatField(verbose_name='The price of the bond (1 lot)')),
                ('maturity', models.DateTimeField(verbose_name='Maturity date of the bonds')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publication')),
                ('cupon', models.FloatField(verbose_name='The cupon of the bond (1 lot)')),
                ('cupon_percent', models.FloatField(verbose_name='The cupon of the bond (1 lot) with %')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
                'ordering': ('-time_update', '-time_create'),
            },
        ),
    ]
