# Generated by Django 3.0.7 on 2020-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200811_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='post', verbose_name='Изображение'),
        ),
    ]
