# Generated by Django 3.0.7 on 2020-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200813_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Blog', verbose_name='Изображение'),
        ),
    ]
