# Generated by Django 3.0.7 on 2021-03-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200913_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=120, verbose_name='Название картинки')),
                ('gallery_text', models.TextField(verbose_name='Текст картинки')),
                ('gallery_views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('gallery_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Gallery', verbose_name='Изображение')),
                ('gallery_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('gallery_comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('gallery_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Gallery')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=120, verbose_name='Название идеи')),
                ('idea_text', models.TextField(verbose_name='Текст идеи')),
                ('idea_views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('idea_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Blog', verbose_name='Изображение')),
                ('idea_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': 'Идеи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('idea_comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Idea')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_title', models.CharField(max_length=150, verbose_name='Название статьи')),
                ('learn_text', models.TextField(verbose_name='Текст статьи')),
                ('learn_views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('learn_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Learn', verbose_name='Обучение')),
                ('learn_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='LearnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('learn_comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('learn_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Learn')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Motiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiv_title', models.CharField(max_length=120, verbose_name='Название мотивации')),
                ('motiv_text', models.TextField(verbose_name='Текст мотивации')),
                ('motiv_views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('motiv_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Motiv', verbose_name='Изображение')),
                ('motiv_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Мотивация',
                'verbose_name_plural': 'Мотивации',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MotivComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiv_author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('motiv_comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('motiv_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Motiv')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
