# Generated by Django 3.0.7 on 2021-03-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210310_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycomment',
            options={'verbose_name': 'Комментарий_Галерея', 'verbose_name_plural': 'Комментарии_Галерея'},
        ),
        migrations.AlterModelOptions(
            name='ideacomment',
            options={'verbose_name': 'Комментарий_Идей', 'verbose_name_plural': 'Комментарии_Идей'},
        ),
        migrations.AlterModelOptions(
            name='learncomment',
            options={'verbose_name': 'Комментарий_Обучения', 'verbose_name_plural': 'Комментарии_Обучения'},
        ),
        migrations.AlterModelOptions(
            name='motivcomment',
            options={'verbose_name': 'Комментарий_Мотивации', 'verbose_name_plural': 'Комментарии_Мотивации'},
        ),
    ]
