# Generated by Django 3.0.7 on 2021-05-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210318_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название идеи')),
                ('text', models.TextField(verbose_name='Текст идеи')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Blog', verbose_name='Изображение')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-id', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticlesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата написании')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-id', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a article genre (e.g. learn, idea, motivation, gallery)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallerycomment',
            name='gallery_title',
        ),
        migrations.RemoveField(
            model_name='ideacomment',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='learncomment',
            name='learn_title',
        ),
        migrations.RemoveField(
            model_name='motivcomment',
            name='motiv_title',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryComment',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='IdeaComment',
        ),
        migrations.DeleteModel(
            name='Learn',
        ),
        migrations.DeleteModel(
            name='LearnComment',
        ),
        migrations.DeleteModel(
            name='Motiv',
        ),
        migrations.DeleteModel(
            name='MotivComment',
        ),
        migrations.AddField(
            model_name='articles',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='articles.Genre'),
        ),
    ]
