# Generated by Django 3.0.7 on 2021-05-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210516_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=120, verbose_name='Название идеи')),
                ('gallery_text', models.TextField(verbose_name='Текст идеи')),
                ('gallery_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('gallery_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Gallery', verbose_name='Изображение')),
                ('gallery_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('gallery_genre', models.ManyToManyField(help_text='Select a genre for this article', to='articles.Genre')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
                'ordering': ['-id', '-gallery_pub_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_gallery', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text_gallery', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('pub_date_gallery', models.DateTimeField(auto_now_add=True, verbose_name='Дата написании')),
                ('article_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Gallery')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-id', '-pub_date_gallery'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=120, verbose_name='Название идеи')),
                ('idea_text', models.TextField(verbose_name='Текст идеи')),
                ('idea_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('idea_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Idea', verbose_name='Изображение')),
                ('idea_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('idea_genre', models.ManyToManyField(help_text='Select a genre for this article', to='articles.Genre')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': 'Идеи',
                'ordering': ['-id', '-idea_pub_date'],
            },
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_idea', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text_idea', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('pub_date_idea', models.DateTimeField(auto_now_add=True, verbose_name='Дата написании')),
                ('article_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Idea')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-id', '-pub_date_idea'],
            },
        ),
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_title', models.CharField(max_length=120, verbose_name='Название идеи')),
                ('learn_text', models.TextField(verbose_name='Текст идеи')),
                ('learn_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('learn_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Learn', verbose_name='Изображение')),
                ('learn_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('learn_genre', models.ManyToManyField(help_text='Select a genre for this article', to='articles.Genre')),
            ],
            options={
                'verbose_name': 'Обучение',
                'verbose_name_plural': 'Обучении',
                'ordering': ['-id', '-learn_pub_date'],
            },
        ),
        migrations.CreateModel(
            name='LearnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_learn', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text_learn', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('pub_date_learn', models.DateTimeField(auto_now_add=True, verbose_name='Дата написании')),
                ('article_learn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Learn')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-id', '-pub_date_learn'],
            },
        ),
        migrations.CreateModel(
            name='Motiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiv_title', models.CharField(max_length=120, verbose_name='Название идеи')),
                ('motiv_text', models.TextField(verbose_name='Текст идеи')),
                ('motiv_views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('motiv_image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='Motiv', verbose_name='Изображение')),
                ('motiv_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('motiv_genre', models.ManyToManyField(help_text='Select a genre for this article', to='articles.Genre')),
            ],
            options={
                'verbose_name': 'Мотивация',
                'verbose_name_plural': 'Мотивации',
                'ordering': ['-id', '-motiv_pub_date'],
            },
        ),
        migrations.CreateModel(
            name='MotivComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_motiv', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('comment_text_motiv', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('pub_date_motiv', models.DateTimeField(auto_now_add=True, verbose_name='Дата написании')),
                ('article_motiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Motiv')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-id', '-pub_date_motiv'],
            },
        ),
        migrations.RemoveField(
            model_name='articlescomment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='ArticlesComment',
        ),
    ]
