# Generated by Django 3.0.7 on 2021-06-23 13:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210520_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='learn',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='motiv',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
