# Generated by Django 3.0.7 on 2021-06-23 14:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20210623_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='content',
        ),
        migrations.RemoveField(
            model_name='motiv',
            name='content',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_text',
            field=tinymce.models.HTMLField(verbose_name='Текст идеи'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_text',
            field=tinymce.models.HTMLField(verbose_name='Текст идеи'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='learn_text',
            field=tinymce.models.HTMLField(verbose_name='Текст идеи'),
        ),
        migrations.AlterField(
            model_name='motiv',
            name='motiv_text',
            field=tinymce.models.HTMLField(verbose_name='Текст идеи'),
        ),
    ]
