# Generated by Django 3.0.7 on 2021-07-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20210623_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycomment',
            name='article_gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryComment',
        ),
    ]
