# Generated by Django 3.0.7 on 2021-12-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20210720_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='learn',
            name='learn_views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='motiv',
            name='motiv_views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
