# Generated by Django 3.0.7 on 2022-04-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20211221_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a article genre (e.g. learn, idea, motivation, gallery)', max_length=256, verbose_name='Категория'),
        ),
    ]
