# Generated by Django 4.2.11 on 2024-07-25 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название статьи', max_length=255, verbose_name='Заголовок статьи')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('slug', models.SlugField(default='', editable=False, max_length=255, verbose_name='URL')),
                ('description', models.TextField(verbose_name='The text of the bond')),
                ('category', models.CharField(choices=[('municipal bonds', 'Municipal bonds'), ('Corporate bonds', 'Corporate bonds'), ('federal loan bonds', 'Federal loan bonds')], max_length=255)),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of change')),
                ('price', models.FloatField(verbose_name='The price of the bond (1 lot)')),
                ('maturity', models.DateTimeField(verbose_name='Maturity date of the bonds')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publication')),
                ('cupon', models.FloatField(verbose_name='The cupon of the bond (1 lot)')),
                ('cupon_percent', models.FloatField(verbose_name='The cupon of the bond (1 lot) with %')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
                'ordering': ('-time_update', '-time_create'),
            },
        ),
    ]
