--
-- PostgreSQL database dump
--

-- Dumped from database version 14.13 (Ubuntu 14.13-1.pgdg22.04+1)
-- Dumped by pg_dump version 14.13 (Ubuntu 14.13-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: articles_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.articles_category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL
);


ALTER TABLE public.articles_category OWNER TO postgres;

--
-- Name: articles_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.articles_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: articles_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.articles_category (id, name, slug) FROM stdin;
1	Центральный банк	tsentralnyj-bank
2	Коррупция	korruptsija
3	Экономика	ekonomika
4	Внешняя политика	vneshnjaja-politika
\.


--
-- Name: articles_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.articles_category_id_seq', 4, true);


--
-- Name: articles_category articles_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.articles_category
    ADD CONSTRAINT articles_category_pkey PRIMARY KEY (id);


--
-- Name: articles_category_slug_f02e70e2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_category_slug_f02e70e2 ON public.articles_category USING btree (slug);


--
-- Name: articles_category_slug_f02e70e2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_category_slug_f02e70e2_like ON public.articles_category USING btree (slug varchar_pattern_ops);


--
-- PostgreSQL database dump complete
--

