# Generated by Django 3.0.7 on 2021-02-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('category', models.IntegerField(blank=True, choices=[('3', 'Есть ошибка на сайте'), ('2', 'У меня есть личный вопрос'), ('1', 'Давай выпьем кофе'), ('0', 'Нужна помощь в финансовой грамотносте')], default='0', max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
                'ordering': ['-id'],
            },
        ),
    ]
