# Generated by Django 3.0.7 on 2021-02-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(blank=True, choices=[('1', 'Давай выпьем кофе'), ('3', 'Есть ошибка на сайте'), ('2', 'У меня есть личный вопрос'), ('0', 'Нужна помощь в финансовой грамотносте')], default='0', max_length=10, null=True),
        ),
    ]
