# Generated by Django 3.0.7 on 2021-02-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210228_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(blank=True, choices=[('1', 'Давай выпьем кофе'), ('0', 'Нужна помощь в финансовой грамотносте'), ('3', 'Есть ошибка на сайте'), ('2', 'У меня есть личный вопрос')], default='0', null=True),
        ),
    ]
