# Generated by Django 3.0.7 on 2021-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210228_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(blank=True, choices=[('4', 'Есть ошибка на сайте'), ('2', 'Давай выпьем кофе'), ('3', 'У меня есть личный вопрос'), ('1', 'Нужна помощь в финансовой грамотносте')], default='0', null=True),
        ),
    ]
