# Generated by Django 3.0.7 on 2021-03-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210304_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
