name: Node Test
on: push
jobs:
  test_node:
    runs-on: ubuntu-latest
    steps:
      - name: Get the directory code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint_node:
    runs-on: ubuntu-latest
    steps:
      - name: Get the directory code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build_node:
    runs-on: ubuntu-latest
    steps:
      - name: Get the directory code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build



